### ISSUE TITLE
rm: cannot remove '/tmp/$USER/makedeb': Permission denied

### ISSUE THREAD

**Issue by logix2** [hwittenborn/mpm#3]
After trying to install the first package (without using sudo), regardless if the installation was successful or not, I get this error when trying to install another package:

```
rm: cannot remove '/tmp/logix/makedeb': Permission denied
Couldn't delete old build directory
```
This is obviously fixed with sudo ``rm -r /tmp/logix``, but mpm should do this.

I'm using mpm 1.2.0-2, makedeb 2.0.6 and makedeb-db 2.0.4 on Ubuntu 21.04.

And another bug which probably doesn't deserve its own bug report: the package ``papirus-icon-theme`` as listed on https://github.com/hwittenborn/mpm/blob/alpha/WORKING_PACKAGES.md doesn't exist in AUR. The actual name is ``papirus-icon-theme-git`` (although installing it doesn't work, so maybe you meant a different package?).

**Comment by hwittenborn** [comment]
I think that's a bug that got left back after I was working on the `alpha` branch a bit, before I had the chance to merge everything to `stable`. Regardless, I'll get it fixed real quick.

> the package papirus-icon-theme as listed on https://github.com/hwittenborn/mpm/blob/alpha/WORKING_PACKAGES.md doesn't exist in AUR

`papirus-icon-theme` is available inside the Arch repositories (support for which is only on the alpha release until I finalize some features, but I expect it to be done within the next few days, if not less).

That's my bad for not clarifying what works with what in `WORKING_PACKAGES.md`, but again, I plan on being done soon, so it shouldn't be an issue for too much longer.

Make sure to take note of the [compatibility changes](https://github.com/hwittenborn/mpm/issues/2) if you decide to upgrade to the alpha release as well.

**Comment by hwittenborn** [comment]
Just upgrade mpm, and everything should be good to go.

If the build directory still exists, you'll probably need to delete it as well.

**Comment by logix2** [comment]
Thanks!
