### ISSUE TITLE
(Report) protonvpn-linux-gui install failed

### ISSUE THREAD

**Issue by ghost** [hwittenborn/mpm#8]
OS - Pop OS based on Ubuntu 20.10
mpm-alpha was used
Error- `Starting package()...
/tmp/a/makedeb/protonvpn-linux-gui/PKGBUILD: line 17: python: command not found
==> ERROR: A failure occurred in package().
    Aborting...
`

**Comment by hwittenborn** [comment]
@cleanerspam Could you try updating your system and building again? I'm pretty sure I've added the necessary packages to `makedeb-db`, but I'm not positive.

**Comment by hwittenborn** [comment]
@cleanerspam Feel free to reopen if the issue still persists.
